//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AristaHRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRISEntities : DbContext
    {
        public HRISEntities()
            : base("name=HRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TM_Cabang> TM_Cabang { get; set; }
        public virtual DbSet<TM_Cuti> TM_Cuti { get; set; }
        public virtual DbSet<TM_Cuti_Bawahan> TM_Cuti_Bawahan { get; set; }
        public virtual DbSet<TM_Cuti_Hangus> TM_Cuti_Hangus { get; set; }
        public virtual DbSet<TM_Default> TM_Default { get; set; }
        public virtual DbSet<TM_File_Manager> TM_File_Manager { get; set; }
        public virtual DbSet<TM_Kalender> TM_Kalender { get; set; }
        public virtual DbSet<TM_Karyawan> TM_Karyawan { get; set; }
        public virtual DbSet<TM_List_Cuti> TM_List_Cuti { get; set; }
        public virtual DbSet<TM_List_Libur> TM_List_Libur { get; set; }
        public virtual DbSet<TM_Mutasi> TM_Mutasi { get; set; }
        public virtual DbSet<TM_Pengumuman> TM_Pengumuman { get; set; }
        public virtual DbSet<TM_Perusahaan> TM_Perusahaan { get; set; }
        public virtual DbSet<TM_Pesan> TM_Pesan { get; set; }
        public virtual DbSet<TM_Riwayat> TM_Riwayat { get; set; }
        public virtual DbSet<TM_Riwayat_Pengajuan> TM_Riwayat_Pengajuan { get; set; }
        public virtual DbSet<TM_Riwayat_User> TM_Riwayat_User { get; set; }
        public virtual DbSet<TM_Sisa_Cuti> TM_Sisa_Cuti { get; set; }
        public virtual DbSet<TM_Wilayah> TM_Wilayah { get; set; }
        public virtual DbSet<TT_Approval_Khusus> TT_Approval_Khusus { get; set; }
        public virtual DbSet<TT_Approval_Tahunan> TT_Approval_Tahunan { get; set; }
        public virtual DbSet<TT_Jumlah_Cuti> TT_Jumlah_Cuti { get; set; }
        public virtual DbSet<TT_Pengajuan> TT_Pengajuan { get; set; }
        public virtual DbSet<TM_Karyawan_Resign> TM_Karyawan_Resign { get; set; }
        public virtual DbSet<TM_Departemen> TM_Departemen { get; set; }
        public virtual DbSet<TM_List_PMK> TM_List_PMK { get; set; }
        public virtual DbSet<TM_StatusWP> TM_StatusWP { get; set; }
    
        public virtual ObjectResult<SM_Cabang_Result1> SM_Cabang(string kode_Cabang, string nama_Perusahaan, string nama_Cabang, string kode_Singkat, string lokasi, string status_Aktif, string kepala_Cabang, string selector)
        {
            var kode_CabangParameter = kode_Cabang != null ?
                new ObjectParameter("Kode_Cabang", kode_Cabang) :
                new ObjectParameter("Kode_Cabang", typeof(string));
    
            var nama_PerusahaanParameter = nama_Perusahaan != null ?
                new ObjectParameter("Nama_Perusahaan", nama_Perusahaan) :
                new ObjectParameter("Nama_Perusahaan", typeof(string));
    
            var nama_CabangParameter = nama_Cabang != null ?
                new ObjectParameter("Nama_Cabang", nama_Cabang) :
                new ObjectParameter("Nama_Cabang", typeof(string));
    
            var kode_SingkatParameter = kode_Singkat != null ?
                new ObjectParameter("Kode_Singkat", kode_Singkat) :
                new ObjectParameter("Kode_Singkat", typeof(string));
    
            var lokasiParameter = lokasi != null ?
                new ObjectParameter("Lokasi", lokasi) :
                new ObjectParameter("Lokasi", typeof(string));
    
            var status_AktifParameter = status_Aktif != null ?
                new ObjectParameter("Status_Aktif", status_Aktif) :
                new ObjectParameter("Status_Aktif", typeof(string));
    
            var kepala_CabangParameter = kepala_Cabang != null ?
                new ObjectParameter("Kepala_Cabang", kepala_Cabang) :
                new ObjectParameter("Kepala_Cabang", typeof(string));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SM_Cabang_Result1>("SM_Cabang", kode_CabangParameter, nama_PerusahaanParameter, nama_CabangParameter, kode_SingkatParameter, lokasiParameter, status_AktifParameter, kepala_CabangParameter, selectorParameter);
        }
    
        public virtual ObjectResult<SM_Karyawan_Result> SM_Karyawan(string nIK, string nIK_Temp, string password, string nama_Karyawan, string jenis_Kelamin, string tempat_Lahir, Nullable<System.DateTime> tgl_Lahir, string provinsi, string kota, string alamat, string agama, string status_Nikah, string email, string email_Perusahaan, string perusahaan, string cabang, string jabatan, string departemen, string nIK_Atasan, string nama_Atasan, string nIK_Supervisor, string nama_Supervisor, string nIK_Advisor, string nama_Advisor, string status_Karyawan, Nullable<System.DateTime> tgl_Masuk, Nullable<System.DateTime> tgl_Resign, string pembuat, string privilege, string notes, string area_Kerja, string nPWP, string status_WP, string noBPJSKS, string noBPJSTK, string createdBy, Nullable<System.DateTime> createdDate, string modifiedBy, Nullable<System.DateTime> modifiedDate, string selector, string nIK_Lama, Nullable<int> email_Valid, Nullable<bool> aktif_Login, Nullable<System.DateTime> last_Login, Nullable<System.DateTime> last_Session)
        {
            var nIKParameter = nIK != null ?
                new ObjectParameter("NIK", nIK) :
                new ObjectParameter("NIK", typeof(string));
    
            var nIK_TempParameter = nIK_Temp != null ?
                new ObjectParameter("NIK_Temp", nIK_Temp) :
                new ObjectParameter("NIK_Temp", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nama_KaryawanParameter = nama_Karyawan != null ?
                new ObjectParameter("Nama_Karyawan", nama_Karyawan) :
                new ObjectParameter("Nama_Karyawan", typeof(string));
    
            var jenis_KelaminParameter = jenis_Kelamin != null ?
                new ObjectParameter("Jenis_Kelamin", jenis_Kelamin) :
                new ObjectParameter("Jenis_Kelamin", typeof(string));
    
            var tempat_LahirParameter = tempat_Lahir != null ?
                new ObjectParameter("Tempat_Lahir", tempat_Lahir) :
                new ObjectParameter("Tempat_Lahir", typeof(string));
    
            var tgl_LahirParameter = tgl_Lahir.HasValue ?
                new ObjectParameter("Tgl_Lahir", tgl_Lahir) :
                new ObjectParameter("Tgl_Lahir", typeof(System.DateTime));
    
            var provinsiParameter = provinsi != null ?
                new ObjectParameter("Provinsi", provinsi) :
                new ObjectParameter("Provinsi", typeof(string));
    
            var kotaParameter = kota != null ?
                new ObjectParameter("Kota", kota) :
                new ObjectParameter("Kota", typeof(string));
    
            var alamatParameter = alamat != null ?
                new ObjectParameter("Alamat", alamat) :
                new ObjectParameter("Alamat", typeof(string));
    
            var agamaParameter = agama != null ?
                new ObjectParameter("Agama", agama) :
                new ObjectParameter("Agama", typeof(string));
    
            var status_NikahParameter = status_Nikah != null ?
                new ObjectParameter("Status_Nikah", status_Nikah) :
                new ObjectParameter("Status_Nikah", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var email_PerusahaanParameter = email_Perusahaan != null ?
                new ObjectParameter("Email_Perusahaan", email_Perusahaan) :
                new ObjectParameter("Email_Perusahaan", typeof(string));
    
            var perusahaanParameter = perusahaan != null ?
                new ObjectParameter("Perusahaan", perusahaan) :
                new ObjectParameter("Perusahaan", typeof(string));
    
            var cabangParameter = cabang != null ?
                new ObjectParameter("Cabang", cabang) :
                new ObjectParameter("Cabang", typeof(string));
    
            var jabatanParameter = jabatan != null ?
                new ObjectParameter("Jabatan", jabatan) :
                new ObjectParameter("Jabatan", typeof(string));
    
            var departemenParameter = departemen != null ?
                new ObjectParameter("Departemen", departemen) :
                new ObjectParameter("Departemen", typeof(string));
    
            var nIK_AtasanParameter = nIK_Atasan != null ?
                new ObjectParameter("NIK_Atasan", nIK_Atasan) :
                new ObjectParameter("NIK_Atasan", typeof(string));
    
            var nama_AtasanParameter = nama_Atasan != null ?
                new ObjectParameter("Nama_Atasan", nama_Atasan) :
                new ObjectParameter("Nama_Atasan", typeof(string));
    
            var nIK_SupervisorParameter = nIK_Supervisor != null ?
                new ObjectParameter("NIK_Supervisor", nIK_Supervisor) :
                new ObjectParameter("NIK_Supervisor", typeof(string));
    
            var nama_SupervisorParameter = nama_Supervisor != null ?
                new ObjectParameter("Nama_Supervisor", nama_Supervisor) :
                new ObjectParameter("Nama_Supervisor", typeof(string));
    
            var nIK_AdvisorParameter = nIK_Advisor != null ?
                new ObjectParameter("NIK_Advisor", nIK_Advisor) :
                new ObjectParameter("NIK_Advisor", typeof(string));
    
            var nama_AdvisorParameter = nama_Advisor != null ?
                new ObjectParameter("Nama_Advisor", nama_Advisor) :
                new ObjectParameter("Nama_Advisor", typeof(string));
    
            var status_KaryawanParameter = status_Karyawan != null ?
                new ObjectParameter("Status_Karyawan", status_Karyawan) :
                new ObjectParameter("Status_Karyawan", typeof(string));
    
            var tgl_MasukParameter = tgl_Masuk.HasValue ?
                new ObjectParameter("Tgl_Masuk", tgl_Masuk) :
                new ObjectParameter("Tgl_Masuk", typeof(System.DateTime));
    
            var tgl_ResignParameter = tgl_Resign.HasValue ?
                new ObjectParameter("Tgl_Resign", tgl_Resign) :
                new ObjectParameter("Tgl_Resign", typeof(System.DateTime));
    
            var pembuatParameter = pembuat != null ?
                new ObjectParameter("Pembuat", pembuat) :
                new ObjectParameter("Pembuat", typeof(string));
    
            var privilegeParameter = privilege != null ?
                new ObjectParameter("Privilege", privilege) :
                new ObjectParameter("Privilege", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            var area_KerjaParameter = area_Kerja != null ?
                new ObjectParameter("Area_Kerja", area_Kerja) :
                new ObjectParameter("Area_Kerja", typeof(string));
    
            var nPWPParameter = nPWP != null ?
                new ObjectParameter("NPWP", nPWP) :
                new ObjectParameter("NPWP", typeof(string));
    
            var status_WPParameter = status_WP != null ?
                new ObjectParameter("Status_WP", status_WP) :
                new ObjectParameter("Status_WP", typeof(string));
    
            var noBPJSKSParameter = noBPJSKS != null ?
                new ObjectParameter("NoBPJSKS", noBPJSKS) :
                new ObjectParameter("NoBPJSKS", typeof(string));
    
            var noBPJSTKParameter = noBPJSTK != null ?
                new ObjectParameter("NoBPJSTK", noBPJSTK) :
                new ObjectParameter("NoBPJSTK", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createdDateParameter = createdDate.HasValue ?
                new ObjectParameter("CreatedDate", createdDate) :
                new ObjectParameter("CreatedDate", typeof(System.DateTime));
    
            var modifiedByParameter = modifiedBy != null ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(string));
    
            var modifiedDateParameter = modifiedDate.HasValue ?
                new ObjectParameter("ModifiedDate", modifiedDate) :
                new ObjectParameter("ModifiedDate", typeof(System.DateTime));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            var nIK_LamaParameter = nIK_Lama != null ?
                new ObjectParameter("NIK_Lama", nIK_Lama) :
                new ObjectParameter("NIK_Lama", typeof(string));
    
            var email_ValidParameter = email_Valid.HasValue ?
                new ObjectParameter("Email_Valid", email_Valid) :
                new ObjectParameter("Email_Valid", typeof(int));
    
            var aktif_LoginParameter = aktif_Login.HasValue ?
                new ObjectParameter("Aktif_Login", aktif_Login) :
                new ObjectParameter("Aktif_Login", typeof(bool));
    
            var last_LoginParameter = last_Login.HasValue ?
                new ObjectParameter("Last_Login", last_Login) :
                new ObjectParameter("Last_Login", typeof(System.DateTime));
    
            var last_SessionParameter = last_Session.HasValue ?
                new ObjectParameter("Last_Session", last_Session) :
                new ObjectParameter("Last_Session", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SM_Karyawan_Result>("SM_Karyawan", nIKParameter, nIK_TempParameter, passwordParameter, nama_KaryawanParameter, jenis_KelaminParameter, tempat_LahirParameter, tgl_LahirParameter, provinsiParameter, kotaParameter, alamatParameter, agamaParameter, status_NikahParameter, emailParameter, email_PerusahaanParameter, perusahaanParameter, cabangParameter, jabatanParameter, departemenParameter, nIK_AtasanParameter, nama_AtasanParameter, nIK_SupervisorParameter, nama_SupervisorParameter, nIK_AdvisorParameter, nama_AdvisorParameter, status_KaryawanParameter, tgl_MasukParameter, tgl_ResignParameter, pembuatParameter, privilegeParameter, notesParameter, area_KerjaParameter, nPWPParameter, status_WPParameter, noBPJSKSParameter, noBPJSTKParameter, createdByParameter, createdDateParameter, modifiedByParameter, modifiedDateParameter, selectorParameter, nIK_LamaParameter, email_ValidParameter, aktif_LoginParameter, last_LoginParameter, last_SessionParameter);
        }
    
        public virtual ObjectResult<SM_List_Cuti_Result> SM_List_Cuti(string iD_Daftar, Nullable<System.DateTime> tgl_Cuti, string jenis_Cuti, string keterangan, Nullable<int> cuti_Massal, Nullable<System.DateTime> tgl_CM, Nullable<int> hari_CM, string selector)
        {
            var iD_DaftarParameter = iD_Daftar != null ?
                new ObjectParameter("ID_Daftar", iD_Daftar) :
                new ObjectParameter("ID_Daftar", typeof(string));
    
            var tgl_CutiParameter = tgl_Cuti.HasValue ?
                new ObjectParameter("Tgl_Cuti", tgl_Cuti) :
                new ObjectParameter("Tgl_Cuti", typeof(System.DateTime));
    
            var jenis_CutiParameter = jenis_Cuti != null ?
                new ObjectParameter("Jenis_Cuti", jenis_Cuti) :
                new ObjectParameter("Jenis_Cuti", typeof(string));
    
            var keteranganParameter = keterangan != null ?
                new ObjectParameter("Keterangan", keterangan) :
                new ObjectParameter("Keterangan", typeof(string));
    
            var cuti_MassalParameter = cuti_Massal.HasValue ?
                new ObjectParameter("Cuti_Massal", cuti_Massal) :
                new ObjectParameter("Cuti_Massal", typeof(int));
    
            var tgl_CMParameter = tgl_CM.HasValue ?
                new ObjectParameter("Tgl_CM", tgl_CM) :
                new ObjectParameter("Tgl_CM", typeof(System.DateTime));
    
            var hari_CMParameter = hari_CM.HasValue ?
                new ObjectParameter("Hari_CM", hari_CM) :
                new ObjectParameter("Hari_CM", typeof(int));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SM_List_Cuti_Result>("SM_List_Cuti", iD_DaftarParameter, tgl_CutiParameter, jenis_CutiParameter, keteranganParameter, cuti_MassalParameter, tgl_CMParameter, hari_CMParameter, selectorParameter);
        }
    
        public virtual ObjectResult<SM_List_Libur_Result> SM_List_Libur(string iD_Daftar, Nullable<System.DateTime> tgl_Libur, string keterangan, Nullable<int> libur_Weekend, string selector)
        {
            var iD_DaftarParameter = iD_Daftar != null ?
                new ObjectParameter("ID_Daftar", iD_Daftar) :
                new ObjectParameter("ID_Daftar", typeof(string));
    
            var tgl_LiburParameter = tgl_Libur.HasValue ?
                new ObjectParameter("Tgl_Libur", tgl_Libur) :
                new ObjectParameter("Tgl_Libur", typeof(System.DateTime));
    
            var keteranganParameter = keterangan != null ?
                new ObjectParameter("Keterangan", keterangan) :
                new ObjectParameter("Keterangan", typeof(string));
    
            var libur_WeekendParameter = libur_Weekend.HasValue ?
                new ObjectParameter("Libur_Weekend", libur_Weekend) :
                new ObjectParameter("Libur_Weekend", typeof(int));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SM_List_Libur_Result>("SM_List_Libur", iD_DaftarParameter, tgl_LiburParameter, keteranganParameter, libur_WeekendParameter, selectorParameter);
        }
    
        public virtual ObjectResult<SM_Perusahaan_Result> SM_Perusahaan(string kode_Perusahaan, string nama_Perusahaan, string kode_Singkat, string selector)
        {
            var kode_PerusahaanParameter = kode_Perusahaan != null ?
                new ObjectParameter("Kode_Perusahaan", kode_Perusahaan) :
                new ObjectParameter("Kode_Perusahaan", typeof(string));
    
            var nama_PerusahaanParameter = nama_Perusahaan != null ?
                new ObjectParameter("Nama_Perusahaan", nama_Perusahaan) :
                new ObjectParameter("Nama_Perusahaan", typeof(string));
    
            var kode_SingkatParameter = kode_Singkat != null ?
                new ObjectParameter("Kode_Singkat", kode_Singkat) :
                new ObjectParameter("Kode_Singkat", typeof(string));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SM_Perusahaan_Result>("SM_Perusahaan", kode_PerusahaanParameter, nama_PerusahaanParameter, kode_SingkatParameter, selectorParameter);
        }
    
        public virtual ObjectResult<SM_Riwayat_Result> SM_Riwayat(string iD_Cuti, string nIK, string nama_Karyawan, string perusahaan, string cabang, string jabatan, string departemen, string nama_Atasan, string nama_Supervisor, string jenis_Cuti, Nullable<System.DateTime> tgl_Pengajuan, Nullable<System.DateTime> tgl_Mulai, Nullable<System.DateTime> tgl_Selesai, string keperluan, string pemberi, string status_Cuti, Nullable<int> tahun_Cuti, Nullable<int> batal, string alasan_Batal, string selector)
        {
            var iD_CutiParameter = iD_Cuti != null ?
                new ObjectParameter("ID_Cuti", iD_Cuti) :
                new ObjectParameter("ID_Cuti", typeof(string));
    
            var nIKParameter = nIK != null ?
                new ObjectParameter("NIK", nIK) :
                new ObjectParameter("NIK", typeof(string));
    
            var nama_KaryawanParameter = nama_Karyawan != null ?
                new ObjectParameter("Nama_Karyawan", nama_Karyawan) :
                new ObjectParameter("Nama_Karyawan", typeof(string));
    
            var perusahaanParameter = perusahaan != null ?
                new ObjectParameter("Perusahaan", perusahaan) :
                new ObjectParameter("Perusahaan", typeof(string));
    
            var cabangParameter = cabang != null ?
                new ObjectParameter("Cabang", cabang) :
                new ObjectParameter("Cabang", typeof(string));
    
            var jabatanParameter = jabatan != null ?
                new ObjectParameter("Jabatan", jabatan) :
                new ObjectParameter("Jabatan", typeof(string));
    
            var departemenParameter = departemen != null ?
                new ObjectParameter("Departemen", departemen) :
                new ObjectParameter("Departemen", typeof(string));
    
            var nama_AtasanParameter = nama_Atasan != null ?
                new ObjectParameter("Nama_Atasan", nama_Atasan) :
                new ObjectParameter("Nama_Atasan", typeof(string));
    
            var nama_SupervisorParameter = nama_Supervisor != null ?
                new ObjectParameter("Nama_Supervisor", nama_Supervisor) :
                new ObjectParameter("Nama_Supervisor", typeof(string));
    
            var jenis_CutiParameter = jenis_Cuti != null ?
                new ObjectParameter("Jenis_Cuti", jenis_Cuti) :
                new ObjectParameter("Jenis_Cuti", typeof(string));
    
            var tgl_PengajuanParameter = tgl_Pengajuan.HasValue ?
                new ObjectParameter("Tgl_Pengajuan", tgl_Pengajuan) :
                new ObjectParameter("Tgl_Pengajuan", typeof(System.DateTime));
    
            var tgl_MulaiParameter = tgl_Mulai.HasValue ?
                new ObjectParameter("Tgl_Mulai", tgl_Mulai) :
                new ObjectParameter("Tgl_Mulai", typeof(System.DateTime));
    
            var tgl_SelesaiParameter = tgl_Selesai.HasValue ?
                new ObjectParameter("Tgl_Selesai", tgl_Selesai) :
                new ObjectParameter("Tgl_Selesai", typeof(System.DateTime));
    
            var keperluanParameter = keperluan != null ?
                new ObjectParameter("Keperluan", keperluan) :
                new ObjectParameter("Keperluan", typeof(string));
    
            var pemberiParameter = pemberi != null ?
                new ObjectParameter("Pemberi", pemberi) :
                new ObjectParameter("Pemberi", typeof(string));
    
            var status_CutiParameter = status_Cuti != null ?
                new ObjectParameter("Status_Cuti", status_Cuti) :
                new ObjectParameter("Status_Cuti", typeof(string));
    
            var tahun_CutiParameter = tahun_Cuti.HasValue ?
                new ObjectParameter("Tahun_Cuti", tahun_Cuti) :
                new ObjectParameter("Tahun_Cuti", typeof(int));
    
            var batalParameter = batal.HasValue ?
                new ObjectParameter("Batal", batal) :
                new ObjectParameter("Batal", typeof(int));
    
            var alasan_BatalParameter = alasan_Batal != null ?
                new ObjectParameter("Alasan_Batal", alasan_Batal) :
                new ObjectParameter("Alasan_Batal", typeof(string));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SM_Riwayat_Result>("SM_Riwayat", iD_CutiParameter, nIKParameter, nama_KaryawanParameter, perusahaanParameter, cabangParameter, jabatanParameter, departemenParameter, nama_AtasanParameter, nama_SupervisorParameter, jenis_CutiParameter, tgl_PengajuanParameter, tgl_MulaiParameter, tgl_SelesaiParameter, keperluanParameter, pemberiParameter, status_CutiParameter, tahun_CutiParameter, batalParameter, alasan_BatalParameter, selectorParameter);
        }
    
        public virtual ObjectResult<SP_ApproveKhusus_Result> SP_ApproveKhusus(string iD_Cuti, string nIK, string nama_Karyawan, string perusahaan, string cabang, string jabatan, string departemen, string nama_Atasan, Nullable<System.DateTime> tgl_Pengajuan, Nullable<System.DateTime> tgl_Setuju, Nullable<System.DateTime> tgl_Mulai, Nullable<System.DateTime> tgl_Selesai, Nullable<int> masa_Cuti, string pemberi, string status_Cuti, string keterangan, string alasan, string jenis_Cuti, string approved_By, Nullable<int> jumlah_Khusus, string selector)
        {
            var iD_CutiParameter = iD_Cuti != null ?
                new ObjectParameter("ID_Cuti", iD_Cuti) :
                new ObjectParameter("ID_Cuti", typeof(string));
    
            var nIKParameter = nIK != null ?
                new ObjectParameter("NIK", nIK) :
                new ObjectParameter("NIK", typeof(string));
    
            var nama_KaryawanParameter = nama_Karyawan != null ?
                new ObjectParameter("Nama_Karyawan", nama_Karyawan) :
                new ObjectParameter("Nama_Karyawan", typeof(string));
    
            var perusahaanParameter = perusahaan != null ?
                new ObjectParameter("Perusahaan", perusahaan) :
                new ObjectParameter("Perusahaan", typeof(string));
    
            var cabangParameter = cabang != null ?
                new ObjectParameter("Cabang", cabang) :
                new ObjectParameter("Cabang", typeof(string));
    
            var jabatanParameter = jabatan != null ?
                new ObjectParameter("Jabatan", jabatan) :
                new ObjectParameter("Jabatan", typeof(string));
    
            var departemenParameter = departemen != null ?
                new ObjectParameter("Departemen", departemen) :
                new ObjectParameter("Departemen", typeof(string));
    
            var nama_AtasanParameter = nama_Atasan != null ?
                new ObjectParameter("Nama_Atasan", nama_Atasan) :
                new ObjectParameter("Nama_Atasan", typeof(string));
    
            var tgl_PengajuanParameter = tgl_Pengajuan.HasValue ?
                new ObjectParameter("Tgl_Pengajuan", tgl_Pengajuan) :
                new ObjectParameter("Tgl_Pengajuan", typeof(System.DateTime));
    
            var tgl_SetujuParameter = tgl_Setuju.HasValue ?
                new ObjectParameter("Tgl_Setuju", tgl_Setuju) :
                new ObjectParameter("Tgl_Setuju", typeof(System.DateTime));
    
            var tgl_MulaiParameter = tgl_Mulai.HasValue ?
                new ObjectParameter("Tgl_Mulai", tgl_Mulai) :
                new ObjectParameter("Tgl_Mulai", typeof(System.DateTime));
    
            var tgl_SelesaiParameter = tgl_Selesai.HasValue ?
                new ObjectParameter("Tgl_Selesai", tgl_Selesai) :
                new ObjectParameter("Tgl_Selesai", typeof(System.DateTime));
    
            var masa_CutiParameter = masa_Cuti.HasValue ?
                new ObjectParameter("Masa_Cuti", masa_Cuti) :
                new ObjectParameter("Masa_Cuti", typeof(int));
    
            var pemberiParameter = pemberi != null ?
                new ObjectParameter("Pemberi", pemberi) :
                new ObjectParameter("Pemberi", typeof(string));
    
            var status_CutiParameter = status_Cuti != null ?
                new ObjectParameter("Status_Cuti", status_Cuti) :
                new ObjectParameter("Status_Cuti", typeof(string));
    
            var keteranganParameter = keterangan != null ?
                new ObjectParameter("Keterangan", keterangan) :
                new ObjectParameter("Keterangan", typeof(string));
    
            var alasanParameter = alasan != null ?
                new ObjectParameter("Alasan", alasan) :
                new ObjectParameter("Alasan", typeof(string));
    
            var jenis_CutiParameter = jenis_Cuti != null ?
                new ObjectParameter("Jenis_Cuti", jenis_Cuti) :
                new ObjectParameter("Jenis_Cuti", typeof(string));
    
            var approved_ByParameter = approved_By != null ?
                new ObjectParameter("Approved_By", approved_By) :
                new ObjectParameter("Approved_By", typeof(string));
    
            var jumlah_KhususParameter = jumlah_Khusus.HasValue ?
                new ObjectParameter("Jumlah_Khusus", jumlah_Khusus) :
                new ObjectParameter("Jumlah_Khusus", typeof(int));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ApproveKhusus_Result>("SP_ApproveKhusus", iD_CutiParameter, nIKParameter, nama_KaryawanParameter, perusahaanParameter, cabangParameter, jabatanParameter, departemenParameter, nama_AtasanParameter, tgl_PengajuanParameter, tgl_SetujuParameter, tgl_MulaiParameter, tgl_SelesaiParameter, masa_CutiParameter, pemberiParameter, status_CutiParameter, keteranganParameter, alasanParameter, jenis_CutiParameter, approved_ByParameter, jumlah_KhususParameter, selectorParameter);
        }
    
        public virtual ObjectResult<SP_ApproveTahunan_Result> SP_ApproveTahunan(string iD_Cuti, string nIK, string nama_Karyawan, string perusahaan, string cabang, string jabatan, string departemen, string nama_Atasan, Nullable<System.DateTime> tgl_Pengajuan, Nullable<System.DateTime> tgl_Setuju, Nullable<System.DateTime> tgl_Mulai, Nullable<System.DateTime> tgl_Selesai, Nullable<int> masa_Cuti, string pemberi, string status_Cuti, string keterangan, string alasan, string jenis_Cuti, string approved_By, Nullable<int> jumlah_Tahunan, Nullable<int> jumlah_Massal, Nullable<int> sisa_Cuti, string selector)
        {
            var iD_CutiParameter = iD_Cuti != null ?
                new ObjectParameter("ID_Cuti", iD_Cuti) :
                new ObjectParameter("ID_Cuti", typeof(string));
    
            var nIKParameter = nIK != null ?
                new ObjectParameter("NIK", nIK) :
                new ObjectParameter("NIK", typeof(string));
    
            var nama_KaryawanParameter = nama_Karyawan != null ?
                new ObjectParameter("Nama_Karyawan", nama_Karyawan) :
                new ObjectParameter("Nama_Karyawan", typeof(string));
    
            var perusahaanParameter = perusahaan != null ?
                new ObjectParameter("Perusahaan", perusahaan) :
                new ObjectParameter("Perusahaan", typeof(string));
    
            var cabangParameter = cabang != null ?
                new ObjectParameter("Cabang", cabang) :
                new ObjectParameter("Cabang", typeof(string));
    
            var jabatanParameter = jabatan != null ?
                new ObjectParameter("Jabatan", jabatan) :
                new ObjectParameter("Jabatan", typeof(string));
    
            var departemenParameter = departemen != null ?
                new ObjectParameter("Departemen", departemen) :
                new ObjectParameter("Departemen", typeof(string));
    
            var nama_AtasanParameter = nama_Atasan != null ?
                new ObjectParameter("Nama_Atasan", nama_Atasan) :
                new ObjectParameter("Nama_Atasan", typeof(string));
    
            var tgl_PengajuanParameter = tgl_Pengajuan.HasValue ?
                new ObjectParameter("Tgl_Pengajuan", tgl_Pengajuan) :
                new ObjectParameter("Tgl_Pengajuan", typeof(System.DateTime));
    
            var tgl_SetujuParameter = tgl_Setuju.HasValue ?
                new ObjectParameter("Tgl_Setuju", tgl_Setuju) :
                new ObjectParameter("Tgl_Setuju", typeof(System.DateTime));
    
            var tgl_MulaiParameter = tgl_Mulai.HasValue ?
                new ObjectParameter("Tgl_Mulai", tgl_Mulai) :
                new ObjectParameter("Tgl_Mulai", typeof(System.DateTime));
    
            var tgl_SelesaiParameter = tgl_Selesai.HasValue ?
                new ObjectParameter("Tgl_Selesai", tgl_Selesai) :
                new ObjectParameter("Tgl_Selesai", typeof(System.DateTime));
    
            var masa_CutiParameter = masa_Cuti.HasValue ?
                new ObjectParameter("Masa_Cuti", masa_Cuti) :
                new ObjectParameter("Masa_Cuti", typeof(int));
    
            var pemberiParameter = pemberi != null ?
                new ObjectParameter("Pemberi", pemberi) :
                new ObjectParameter("Pemberi", typeof(string));
    
            var status_CutiParameter = status_Cuti != null ?
                new ObjectParameter("Status_Cuti", status_Cuti) :
                new ObjectParameter("Status_Cuti", typeof(string));
    
            var keteranganParameter = keterangan != null ?
                new ObjectParameter("Keterangan", keterangan) :
                new ObjectParameter("Keterangan", typeof(string));
    
            var alasanParameter = alasan != null ?
                new ObjectParameter("Alasan", alasan) :
                new ObjectParameter("Alasan", typeof(string));
    
            var jenis_CutiParameter = jenis_Cuti != null ?
                new ObjectParameter("Jenis_Cuti", jenis_Cuti) :
                new ObjectParameter("Jenis_Cuti", typeof(string));
    
            var approved_ByParameter = approved_By != null ?
                new ObjectParameter("Approved_By", approved_By) :
                new ObjectParameter("Approved_By", typeof(string));
    
            var jumlah_TahunanParameter = jumlah_Tahunan.HasValue ?
                new ObjectParameter("Jumlah_Tahunan", jumlah_Tahunan) :
                new ObjectParameter("Jumlah_Tahunan", typeof(int));
    
            var jumlah_MassalParameter = jumlah_Massal.HasValue ?
                new ObjectParameter("Jumlah_Massal", jumlah_Massal) :
                new ObjectParameter("Jumlah_Massal", typeof(int));
    
            var sisa_CutiParameter = sisa_Cuti.HasValue ?
                new ObjectParameter("Sisa_Cuti", sisa_Cuti) :
                new ObjectParameter("Sisa_Cuti", typeof(int));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ApproveTahunan_Result>("SP_ApproveTahunan", iD_CutiParameter, nIKParameter, nama_KaryawanParameter, perusahaanParameter, cabangParameter, jabatanParameter, departemenParameter, nama_AtasanParameter, tgl_PengajuanParameter, tgl_SetujuParameter, tgl_MulaiParameter, tgl_SelesaiParameter, masa_CutiParameter, pemberiParameter, status_CutiParameter, keteranganParameter, alasanParameter, jenis_CutiParameter, approved_ByParameter, jumlah_TahunanParameter, jumlah_MassalParameter, sisa_CutiParameter, selectorParameter);
        }
    
        public virtual int SP_Hitung_Cuti_Hangus(string nIK, string nama_Karyawan, string perusahaan, string cabang, string jabatan, string departemen, string nama_Atasan, string nama_Supervisor, Nullable<System.DateTime> tgl_Masuk, Nullable<System.DateTime> tgl_Akhir, Nullable<System.DateTime> tgl_Resign, string temp1, Nullable<int> temp2, Nullable<int> temp3, Nullable<int> temp4, Nullable<int> temp5, Nullable<int> jatah_Cuti, Nullable<int> total_Cuti, Nullable<int> periode1, Nullable<int> periode2, Nullable<int> cuti_Pribadi, Nullable<int> cuti_Khusus, Nullable<int> cuti_Massal)
        {
            var nIKParameter = nIK != null ?
                new ObjectParameter("NIK", nIK) :
                new ObjectParameter("NIK", typeof(string));
    
            var nama_KaryawanParameter = nama_Karyawan != null ?
                new ObjectParameter("Nama_Karyawan", nama_Karyawan) :
                new ObjectParameter("Nama_Karyawan", typeof(string));
    
            var perusahaanParameter = perusahaan != null ?
                new ObjectParameter("Perusahaan", perusahaan) :
                new ObjectParameter("Perusahaan", typeof(string));
    
            var cabangParameter = cabang != null ?
                new ObjectParameter("Cabang", cabang) :
                new ObjectParameter("Cabang", typeof(string));
    
            var jabatanParameter = jabatan != null ?
                new ObjectParameter("Jabatan", jabatan) :
                new ObjectParameter("Jabatan", typeof(string));
    
            var departemenParameter = departemen != null ?
                new ObjectParameter("Departemen", departemen) :
                new ObjectParameter("Departemen", typeof(string));
    
            var nama_AtasanParameter = nama_Atasan != null ?
                new ObjectParameter("Nama_Atasan", nama_Atasan) :
                new ObjectParameter("Nama_Atasan", typeof(string));
    
            var nama_SupervisorParameter = nama_Supervisor != null ?
                new ObjectParameter("Nama_Supervisor", nama_Supervisor) :
                new ObjectParameter("Nama_Supervisor", typeof(string));
    
            var tgl_MasukParameter = tgl_Masuk.HasValue ?
                new ObjectParameter("Tgl_Masuk", tgl_Masuk) :
                new ObjectParameter("Tgl_Masuk", typeof(System.DateTime));
    
            var tgl_AkhirParameter = tgl_Akhir.HasValue ?
                new ObjectParameter("Tgl_Akhir", tgl_Akhir) :
                new ObjectParameter("Tgl_Akhir", typeof(System.DateTime));
    
            var tgl_ResignParameter = tgl_Resign.HasValue ?
                new ObjectParameter("Tgl_Resign", tgl_Resign) :
                new ObjectParameter("Tgl_Resign", typeof(System.DateTime));
    
            var temp1Parameter = temp1 != null ?
                new ObjectParameter("Temp1", temp1) :
                new ObjectParameter("Temp1", typeof(string));
    
            var temp2Parameter = temp2.HasValue ?
                new ObjectParameter("Temp2", temp2) :
                new ObjectParameter("Temp2", typeof(int));
    
            var temp3Parameter = temp3.HasValue ?
                new ObjectParameter("Temp3", temp3) :
                new ObjectParameter("Temp3", typeof(int));
    
            var temp4Parameter = temp4.HasValue ?
                new ObjectParameter("Temp4", temp4) :
                new ObjectParameter("Temp4", typeof(int));
    
            var temp5Parameter = temp5.HasValue ?
                new ObjectParameter("Temp5", temp5) :
                new ObjectParameter("Temp5", typeof(int));
    
            var jatah_CutiParameter = jatah_Cuti.HasValue ?
                new ObjectParameter("Jatah_Cuti", jatah_Cuti) :
                new ObjectParameter("Jatah_Cuti", typeof(int));
    
            var total_CutiParameter = total_Cuti.HasValue ?
                new ObjectParameter("Total_Cuti", total_Cuti) :
                new ObjectParameter("Total_Cuti", typeof(int));
    
            var periode1Parameter = periode1.HasValue ?
                new ObjectParameter("Periode1", periode1) :
                new ObjectParameter("Periode1", typeof(int));
    
            var periode2Parameter = periode2.HasValue ?
                new ObjectParameter("Periode2", periode2) :
                new ObjectParameter("Periode2", typeof(int));
    
            var cuti_PribadiParameter = cuti_Pribadi.HasValue ?
                new ObjectParameter("Cuti_Pribadi", cuti_Pribadi) :
                new ObjectParameter("Cuti_Pribadi", typeof(int));
    
            var cuti_KhususParameter = cuti_Khusus.HasValue ?
                new ObjectParameter("Cuti_Khusus", cuti_Khusus) :
                new ObjectParameter("Cuti_Khusus", typeof(int));
    
            var cuti_MassalParameter = cuti_Massal.HasValue ?
                new ObjectParameter("Cuti_Massal", cuti_Massal) :
                new ObjectParameter("Cuti_Massal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Hitung_Cuti_Hangus", nIKParameter, nama_KaryawanParameter, perusahaanParameter, cabangParameter, jabatanParameter, departemenParameter, nama_AtasanParameter, nama_SupervisorParameter, tgl_MasukParameter, tgl_AkhirParameter, tgl_ResignParameter, temp1Parameter, temp2Parameter, temp3Parameter, temp4Parameter, temp5Parameter, jatah_CutiParameter, total_CutiParameter, periode1Parameter, periode2Parameter, cuti_PribadiParameter, cuti_KhususParameter, cuti_MassalParameter);
        }
    
        public virtual int SP_Hitung_Cuti_Tahunan(string nIK, string nama_Karyawan, string nama_Atasan, string nama_Advisor, Nullable<System.DateTime> tgl_Masuk, Nullable<System.DateTime> tgl_Akhir, string temp1, Nullable<int> temp5, string selector)
        {
            var nIKParameter = nIK != null ?
                new ObjectParameter("NIK", nIK) :
                new ObjectParameter("NIK", typeof(string));
    
            var nama_KaryawanParameter = nama_Karyawan != null ?
                new ObjectParameter("Nama_Karyawan", nama_Karyawan) :
                new ObjectParameter("Nama_Karyawan", typeof(string));
    
            var nama_AtasanParameter = nama_Atasan != null ?
                new ObjectParameter("Nama_Atasan", nama_Atasan) :
                new ObjectParameter("Nama_Atasan", typeof(string));
    
            var nama_AdvisorParameter = nama_Advisor != null ?
                new ObjectParameter("Nama_Advisor", nama_Advisor) :
                new ObjectParameter("Nama_Advisor", typeof(string));
    
            var tgl_MasukParameter = tgl_Masuk.HasValue ?
                new ObjectParameter("Tgl_Masuk", tgl_Masuk) :
                new ObjectParameter("Tgl_Masuk", typeof(System.DateTime));
    
            var tgl_AkhirParameter = tgl_Akhir.HasValue ?
                new ObjectParameter("Tgl_Akhir", tgl_Akhir) :
                new ObjectParameter("Tgl_Akhir", typeof(System.DateTime));
    
            var temp1Parameter = temp1 != null ?
                new ObjectParameter("Temp1", temp1) :
                new ObjectParameter("Temp1", typeof(string));
    
            var temp5Parameter = temp5.HasValue ?
                new ObjectParameter("Temp5", temp5) :
                new ObjectParameter("Temp5", typeof(int));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Hitung_Cuti_Tahunan", nIKParameter, nama_KaryawanParameter, nama_AtasanParameter, nama_AdvisorParameter, tgl_MasukParameter, tgl_AkhirParameter, temp1Parameter, temp5Parameter, selectorParameter);
        }
    
        public virtual ObjectResult<SP_Masa_Cuti_Result> SP_Masa_Cuti(Nullable<System.DateTime> tgl_Mulai, Nullable<System.DateTime> tgl_Selesai, Nullable<int> hari_Per_Pekan, ObjectParameter jumlah_Hari)
        {
            var tgl_MulaiParameter = tgl_Mulai.HasValue ?
                new ObjectParameter("Tgl_Mulai", tgl_Mulai) :
                new ObjectParameter("Tgl_Mulai", typeof(System.DateTime));
    
            var tgl_SelesaiParameter = tgl_Selesai.HasValue ?
                new ObjectParameter("Tgl_Selesai", tgl_Selesai) :
                new ObjectParameter("Tgl_Selesai", typeof(System.DateTime));
    
            var hari_Per_PekanParameter = hari_Per_Pekan.HasValue ?
                new ObjectParameter("Hari_Per_Pekan", hari_Per_Pekan) :
                new ObjectParameter("Hari_Per_Pekan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Masa_Cuti_Result>("SP_Masa_Cuti", tgl_MulaiParameter, tgl_SelesaiParameter, hari_Per_PekanParameter, jumlah_Hari);
        }
    
        public virtual int SP_Masa_Cuti_Cabang(Nullable<System.DateTime> tgl_Mulai, Nullable<System.DateTime> tgl_Selesai, Nullable<int> hari_Per_Pekan, ObjectParameter jumlah_Hari)
        {
            var tgl_MulaiParameter = tgl_Mulai.HasValue ?
                new ObjectParameter("Tgl_Mulai", tgl_Mulai) :
                new ObjectParameter("Tgl_Mulai", typeof(System.DateTime));
    
            var tgl_SelesaiParameter = tgl_Selesai.HasValue ?
                new ObjectParameter("Tgl_Selesai", tgl_Selesai) :
                new ObjectParameter("Tgl_Selesai", typeof(System.DateTime));
    
            var hari_Per_PekanParameter = hari_Per_Pekan.HasValue ?
                new ObjectParameter("Hari_Per_Pekan", hari_Per_Pekan) :
                new ObjectParameter("Hari_Per_Pekan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Masa_Cuti_Cabang", tgl_MulaiParameter, tgl_SelesaiParameter, hari_Per_PekanParameter, jumlah_Hari);
        }
    
        public virtual ObjectResult<SP_Pengajuan_Result> SP_Pengajuan(string iD_Cuti, string nIK, string nama_Karyawan, string jenis_Kelamin, string agama, string status_Nikah, string perusahaan, string cabang, string jabatan, string departemen, Nullable<System.DateTime> tgl_Masuk, string nama_Atasan, string nama_Supervisor, string jenis_Cuti, string keperluan, Nullable<System.DateTime> tgl_Pengajuan, Nullable<System.DateTime> tgl_Setuju, Nullable<System.DateTime> tgl_Mulai, Nullable<System.DateTime> tgl_Selesai, Nullable<int> masa_Cuti, string pemberi, string status_Cuti, string keterangan, string alasan, string lokasi, string nomor_Kontak, Nullable<int> tahun_Cuti, string user_Login, string selector)
        {
            var iD_CutiParameter = iD_Cuti != null ?
                new ObjectParameter("ID_Cuti", iD_Cuti) :
                new ObjectParameter("ID_Cuti", typeof(string));
    
            var nIKParameter = nIK != null ?
                new ObjectParameter("NIK", nIK) :
                new ObjectParameter("NIK", typeof(string));
    
            var nama_KaryawanParameter = nama_Karyawan != null ?
                new ObjectParameter("Nama_Karyawan", nama_Karyawan) :
                new ObjectParameter("Nama_Karyawan", typeof(string));
    
            var jenis_KelaminParameter = jenis_Kelamin != null ?
                new ObjectParameter("Jenis_Kelamin", jenis_Kelamin) :
                new ObjectParameter("Jenis_Kelamin", typeof(string));
    
            var agamaParameter = agama != null ?
                new ObjectParameter("Agama", agama) :
                new ObjectParameter("Agama", typeof(string));
    
            var status_NikahParameter = status_Nikah != null ?
                new ObjectParameter("Status_Nikah", status_Nikah) :
                new ObjectParameter("Status_Nikah", typeof(string));
    
            var perusahaanParameter = perusahaan != null ?
                new ObjectParameter("Perusahaan", perusahaan) :
                new ObjectParameter("Perusahaan", typeof(string));
    
            var cabangParameter = cabang != null ?
                new ObjectParameter("Cabang", cabang) :
                new ObjectParameter("Cabang", typeof(string));
    
            var jabatanParameter = jabatan != null ?
                new ObjectParameter("Jabatan", jabatan) :
                new ObjectParameter("Jabatan", typeof(string));
    
            var departemenParameter = departemen != null ?
                new ObjectParameter("Departemen", departemen) :
                new ObjectParameter("Departemen", typeof(string));
    
            var tgl_MasukParameter = tgl_Masuk.HasValue ?
                new ObjectParameter("Tgl_Masuk", tgl_Masuk) :
                new ObjectParameter("Tgl_Masuk", typeof(System.DateTime));
    
            var nama_AtasanParameter = nama_Atasan != null ?
                new ObjectParameter("Nama_Atasan", nama_Atasan) :
                new ObjectParameter("Nama_Atasan", typeof(string));
    
            var nama_SupervisorParameter = nama_Supervisor != null ?
                new ObjectParameter("Nama_Supervisor", nama_Supervisor) :
                new ObjectParameter("Nama_Supervisor", typeof(string));
    
            var jenis_CutiParameter = jenis_Cuti != null ?
                new ObjectParameter("Jenis_Cuti", jenis_Cuti) :
                new ObjectParameter("Jenis_Cuti", typeof(string));
    
            var keperluanParameter = keperluan != null ?
                new ObjectParameter("Keperluan", keperluan) :
                new ObjectParameter("Keperluan", typeof(string));
    
            var tgl_PengajuanParameter = tgl_Pengajuan.HasValue ?
                new ObjectParameter("Tgl_Pengajuan", tgl_Pengajuan) :
                new ObjectParameter("Tgl_Pengajuan", typeof(System.DateTime));
    
            var tgl_SetujuParameter = tgl_Setuju.HasValue ?
                new ObjectParameter("Tgl_Setuju", tgl_Setuju) :
                new ObjectParameter("Tgl_Setuju", typeof(System.DateTime));
    
            var tgl_MulaiParameter = tgl_Mulai.HasValue ?
                new ObjectParameter("Tgl_Mulai", tgl_Mulai) :
                new ObjectParameter("Tgl_Mulai", typeof(System.DateTime));
    
            var tgl_SelesaiParameter = tgl_Selesai.HasValue ?
                new ObjectParameter("Tgl_Selesai", tgl_Selesai) :
                new ObjectParameter("Tgl_Selesai", typeof(System.DateTime));
    
            var masa_CutiParameter = masa_Cuti.HasValue ?
                new ObjectParameter("Masa_Cuti", masa_Cuti) :
                new ObjectParameter("Masa_Cuti", typeof(int));
    
            var pemberiParameter = pemberi != null ?
                new ObjectParameter("Pemberi", pemberi) :
                new ObjectParameter("Pemberi", typeof(string));
    
            var status_CutiParameter = status_Cuti != null ?
                new ObjectParameter("Status_Cuti", status_Cuti) :
                new ObjectParameter("Status_Cuti", typeof(string));
    
            var keteranganParameter = keterangan != null ?
                new ObjectParameter("Keterangan", keterangan) :
                new ObjectParameter("Keterangan", typeof(string));
    
            var alasanParameter = alasan != null ?
                new ObjectParameter("Alasan", alasan) :
                new ObjectParameter("Alasan", typeof(string));
    
            var lokasiParameter = lokasi != null ?
                new ObjectParameter("Lokasi", lokasi) :
                new ObjectParameter("Lokasi", typeof(string));
    
            var nomor_KontakParameter = nomor_Kontak != null ?
                new ObjectParameter("Nomor_Kontak", nomor_Kontak) :
                new ObjectParameter("Nomor_Kontak", typeof(string));
    
            var tahun_CutiParameter = tahun_Cuti.HasValue ?
                new ObjectParameter("Tahun_Cuti", tahun_Cuti) :
                new ObjectParameter("Tahun_Cuti", typeof(int));
    
            var user_LoginParameter = user_Login != null ?
                new ObjectParameter("User_Login", user_Login) :
                new ObjectParameter("User_Login", typeof(string));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Pengajuan_Result>("SP_Pengajuan", iD_CutiParameter, nIKParameter, nama_KaryawanParameter, jenis_KelaminParameter, agamaParameter, status_NikahParameter, perusahaanParameter, cabangParameter, jabatanParameter, departemenParameter, tgl_MasukParameter, nama_AtasanParameter, nama_SupervisorParameter, jenis_CutiParameter, keperluanParameter, tgl_PengajuanParameter, tgl_SetujuParameter, tgl_MulaiParameter, tgl_SelesaiParameter, masa_CutiParameter, pemberiParameter, status_CutiParameter, keteranganParameter, alasanParameter, lokasiParameter, nomor_KontakParameter, tahun_CutiParameter, user_LoginParameter, selectorParameter);
        }
    
        public virtual ObjectResult<SP_Pengumuman_Result> SP_Pengumuman(string iD_Daftar, string jenis_Anno, Nullable<System.DateTime> tgl_Anno, string keterangan, string selector)
        {
            var iD_DaftarParameter = iD_Daftar != null ?
                new ObjectParameter("ID_Daftar", iD_Daftar) :
                new ObjectParameter("ID_Daftar", typeof(string));
    
            var jenis_AnnoParameter = jenis_Anno != null ?
                new ObjectParameter("Jenis_Anno", jenis_Anno) :
                new ObjectParameter("Jenis_Anno", typeof(string));
    
            var tgl_AnnoParameter = tgl_Anno.HasValue ?
                new ObjectParameter("Tgl_Anno", tgl_Anno) :
                new ObjectParameter("Tgl_Anno", typeof(System.DateTime));
    
            var keteranganParameter = keterangan != null ?
                new ObjectParameter("Keterangan", keterangan) :
                new ObjectParameter("Keterangan", typeof(string));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Pengumuman_Result>("SP_Pengumuman", iD_DaftarParameter, jenis_AnnoParameter, tgl_AnnoParameter, keteranganParameter, selectorParameter);
        }
    
        public virtual int SP_Riwayat_Pengajuan(Nullable<int> tahun_Cuti, Nullable<int> total_Cuti, string selector)
        {
            var tahun_CutiParameter = tahun_Cuti.HasValue ?
                new ObjectParameter("Tahun_Cuti", tahun_Cuti) :
                new ObjectParameter("Tahun_Cuti", typeof(int));
    
            var total_CutiParameter = total_Cuti.HasValue ?
                new ObjectParameter("Total_Cuti", total_Cuti) :
                new ObjectParameter("Total_Cuti", typeof(int));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Riwayat_Pengajuan", tahun_CutiParameter, total_CutiParameter, selectorParameter);
        }
    
        public virtual int SP_Riwayat_User(string nama_Karyawan, string nama_Atasan, Nullable<int> tahun_Cuti, string selector)
        {
            var nama_KaryawanParameter = nama_Karyawan != null ?
                new ObjectParameter("Nama_Karyawan", nama_Karyawan) :
                new ObjectParameter("Nama_Karyawan", typeof(string));
    
            var nama_AtasanParameter = nama_Atasan != null ?
                new ObjectParameter("Nama_Atasan", nama_Atasan) :
                new ObjectParameter("Nama_Atasan", typeof(string));
    
            var tahun_CutiParameter = tahun_Cuti.HasValue ?
                new ObjectParameter("Tahun_Cuti", tahun_Cuti) :
                new ObjectParameter("Tahun_Cuti", typeof(int));
    
            var selectorParameter = selector != null ?
                new ObjectParameter("Selector", selector) :
                new ObjectParameter("Selector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Riwayat_User", nama_KaryawanParameter, nama_AtasanParameter, tahun_CutiParameter, selectorParameter);
        }
    }
}
