//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AristaHRM.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class TM_Cuti_Bawahan
    {
        [Key]
        public string ID_Cuti { get; set; }
        public string NIK { get; set; }
        public string Nama_Karyawan { get; set; }
        public string Nama_Atasan { get; set; }
        public string Nama_Advisor { get; set; }
        public Nullable<System.DateTime> Tgl_Masuk { get; set; }
        public Nullable<System.DateTime> Periode_Awal { get; set; }
        public Nullable<System.DateTime> Periode_Akhir { get; set; }
        public Nullable<int> Jatah_Cuti { get; set; }
        public Nullable<int> Total_Cuti { get; set; }
        public Nullable<int> Cuti_Pribadi { get; set; }
        public Nullable<int> Cuti_Khusus { get; set; }
        public Nullable<int> Cuti_Massal { get; set; }
        public Nullable<int> Cuti_Hangus { get; set; }
        public Nullable<int> Tahun_Hangus { get; set; }
        public Nullable<int> Cuti_Sekarang { get; set; }
        public Nullable<int> Sisa_Cuti { get; set; }
        public Nullable<int> Tahun_Cuti { get; set; }
    }
}
