//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AristaHRM.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class TM_Default
    {
        [Key]
        public string ID_Jenis { get; set; }
        public string Kode_Jenis { get; set; }
        public string ID_Isi { get; set; }
        public string Jenis_Isi { get; set; }
        public string Keterangan { get; set; }
        public Nullable<int> Jumlah_Hari { get; set; }
        public string Tambahan { get; set; }
    }
}
