//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AristaHRM.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class TM_Karyawan
    {
        [Key]
        public string NIK { get; set; }
        public string Nama_Karyawan { get; set; }
        public string Password { get; set; }
        public string Jenis_Kelamin { get; set; }
        public string Tempat_Lahir { get; set; }
        public Nullable<System.DateTime> Tgl_Lahir { get; set; }
        public string Provinsi { get; set; }
        public string Kota { get; set; }
        public string Alamat { get; set; }
        public string Agama { get; set; }
        public string Status_Nikah { get; set; }
        public string Email { get; set; }
        public string Email_Perusahaan { get; set; }
        public string Perusahaan { get; set; }
        public string Cabang { get; set; }
        public string Jabatan { get; set; }
        public string Departemen { get; set; }
        public string Nama_Atasan { get; set; }
        public string Nama_Supervisor { get; set; }
        public string Nama_Advisor { get; set; }
        public Nullable<System.DateTime> Tgl_Masuk { get; set; }
        public Nullable<System.DateTime> Tgl_Resign { get; set; }
        public string Status_Karyawan { get; set; }
        public string Status_Kerja { get; set; }
        public Nullable<int> Email_Valid { get; set; }
        public string Pembuat { get; set; }
        public string Privilege { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
        public Nullable<System.DateTime> Last_Session { get; set; }
        public bool Aktif_Login { get; set; }
        public string Area_Kerja { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string NIK_Atasan { get; set; }
        public string NIK_Supervisor { get; set; }
        public string NIK_Advisor { get; set; }
        public string NPWP { get; set; }
        public string Status_WP { get; set; }
        public string NIK_Temp { get; set; }
        public string NoBPJSTK { get; set; }
        public string NoBPJSKS { get; set; }
    }
}
