//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AristaHRM.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class TM_Karyawan_Resign
    {
        [Key]
        public string NIK { get; set; }
        public string Nama_Karyawan { get; set; }
        public string Perusahaan { get; set; }
        public string Cabang { get; set; }
        public string Jabatan { get; set; }
        public string Departemen { get; set; }
        public string Nama_Atasan { get; set; }
        public string Nama_Supervisor { get; set; }
        public Nullable<System.DateTime> Tgl_Resign { get; set; }
        public string Alasan { get; set; }
        public string Status_Resign { get; set; }
    }
}
