//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AristaHRM.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class TM_List_PMK
    {
        [Key]
        public long ID_PMK { get; set; }
        public string No_PMK { get; set; }
        public Nullable<System.DateTime> Tgl_PMK { get; set; }
        public string Jenis_PMK { get; set; }
        public string NIK_Asal { get; set; }
        public string Perusahaan_Asal { get; set; }
        public string Cabang_Asal { get; set; }
        public string Jabatan_Asal { get; set; }
        public string Departemen_Asal { get; set; }
        public string NIK_Baru { get; set; }
        public string Perusahaan_Baru { get; set; }
        public string Cabang_Baru { get; set; }
        public string Jabatan_Baru { get; set; }
        public string Departemen_Baru { get; set; }
        public Nullable<System.DateTime> Tgl_Efektif { get; set; }
        public string Status_Asal { get; set; }
        public string Status_Baru { get; set; }
        public string Alasan { get; set; }
        public string Notes { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
