//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AristaHRM.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class TM_List_Cuti
    {
        [Key]
        public string ID_Daftar { get; set; }
        public Nullable<System.DateTime> Tgl_Cuti { get; set; }
        public string Jenis_Cuti { get; set; }
        public string Keterangan { get; set; }
        public Nullable<int> Cuti_Massal { get; set; }
    }
}
