//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AristaHRM.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class TM_Mutasi
    {
        [Key]
        public string ID_Mutasi { get; set; }
        public string NIK { get; set; }
        public string Nama_Karyawan { get; set; }
        public string Perusahaan { get; set; }
        public string Cabang { get; set; }
        public string Jabatan { get; set; }
        public string Departemen { get; set; }
        public string Perusahaan_Baru { get; set; }
        public string Cabang_Baru { get; set; }
        public string Jabatan_Baru { get; set; }
        public string Departemen_Baru { get; set; }
        public string Atasan_Baru { get; set; }
        public string Supervisor_Baru { get; set; }
        public string Atasan_Ganti { get; set; }
        public Nullable<System.DateTime> Tgl_Mutasi { get; set; }
        public string Keterangan { get; set; }
        public string Atasan_Asal { get; set; }
        public string Staf_Ganti { get; set; }
        public string NIK_Atasan_Baru { get; set; }
    }
}
