//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AristaHRM.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class TM_Pesan
    {
        [Key]
        public string ID_Pesan { get; set; }
        public string NIK { get; set; }
        public string Nama_Karyawan { get; set; }
        public string Perusahaan { get; set; }
        public string Cabang { get; set; }
        public string Jabatan { get; set; }
        public string Departemen { get; set; }
        public string Subjek { get; set; }
        public string Isi_Pesan { get; set; }
        public Nullable<System.DateTime> Tgl_Kirim { get; set; }
        public string Tanggapan { get; set; }
        public string Alasan { get; set; }
        public Nullable<System.DateTime> Tgl_Jawab { get; set; }
    }
}
